const chords = {
    crazy: [
        { name: "chordAb7#9", description: "Ab, C, Eb, Gb, Bb" },
        { name: "chordAm(maj7)", description: "A, C, E, G#" },
        { name: "chordAm(#5)", description: "A, C, E#" },
        { name: "chordAm9", description: "A, C, E, G, B" },
        { name: "chordB7(b9)", description: "B, D#, F#, A, C" },
        { name: "chordBb7sus2", description: "Bb, C, F, Ab" },
        { name: "chordBm9", description: "B, D, F#, A, C#" },
        { name: "chordBsus2", description: "B, C#, F#" },
        { name: "chordC7", description: "C, E, G, Bb" },
        { name: "chordC13(b5)", description: "C, E, Gb, Bb, D, A" },
        { name: "chordCadd9", description: "C, E, G, D" },
        { name: "chordCm(maj7,b9,#5)", description: "C, Eb, G#, B, Db" },
        { name: "chordD7sus2", description: "D, E, A, C" },
        { name: "chordDm7", description: "D, F, A, C" },
        { name: "chordE7sus4(#5)", description: "E, A, B#, D" },
        { name: "chordEb7", description: "Eb, G, Bb, Db" },
        { name: "chordEbm7", description: "Eb, Gb, Bb, Db"},
        { name: "chordEbm(maj7,9,#5)", description: "Eb, Gb, B, D, F" },
        { name: "chordEsus4(add9)", description: "E, A, B, F#" },
        { name: "chordF9", description: "F, A, C, Eb, G" },
        { name: "chordF#mb5", description: "F#, A, C" },
        { name: "chordG7(#5,#9)", description: "G, B, D#, F, A#" },
        { name: "chordG7#5", description: "G, B, D#, F" },
        { name: "chordGsus4", description: "G, C, D" }, 
    ],

    triad: [
        { name: "chordA", description: "A, C#, E" },
        { name: "chordAbm", description: "Ab, Cb, Eb" },
        { name: "chordAm", description: "A, C, E" },
        { name: "chordB", description: "B, D#, F#" },
        { name: "chordBdim", description: "B, D, F"},
        { name: "chordBbm", description: "Bb, Db, F" },
        { name: "chordC", description: "C, E, G" },
        { name: "chordCaug", description: "C, E, G#" },
        { name: "chordCm", description: "C, Eb, G" },
        { name: "chordDaug", description: "D, F#, A#" },
        { name: "chordDb", description: "Db, F, Ab" },
        { name: "chordDm", description: "D, F, A" },
        { name: "chordE", description: "E, G#, B" },
        { name: "chordEaug", description: "E, G#, C" },
        { name: "chordEb", description: "Eb, G, Bb" },
        { name: "chordEbm", description: "Eb, Gb, Bb" },
        { name: "chordF", description: "F, A, C" },
        { name: "chordFdim", description: "F, Ab, B" },
        { name: "chordF#m", description: "F#, A, C#" },
        { name: "chordG", description: "G, B, D" },
        { name: "chordGaug", description: "G, B, D#" },
        { name: "chordGbm", description: "Gb, Bbb, Db" },
        { name: "chordGm", description: "G, Bb, D" },
        { name: "chordG#dim", description: "G#, B, D" }
    ],

    note: [
        { name: "trebleA3", description: "This treble space note is on the second staff space from the bottom" },
        { name: "trebleA4", description: "This treble space note is on the second staff space from the bottom" },
        { name: "trebleA5", description: "This treble space note is on the first ledger space above the staff" },
        { name: "trebleA#3", description: "This treble sharp space note is on the second staff space from the bottom" },
        { name: "trebleB3", description: "This treble line note is on the third staff line from the bottom" },
        { name: "trebleB4", description: "This treble line note is on the third staff line from the bottom" },
        { name: "trebleB5", description: "This treble line note is on the first ledger line above the staff" },
        { name: "trebleBb3", description: "This treble flat line note is on the third staff line from the bottom" },
        { name: "trebleC4", description: "This treble line note is on the first ledger line below the staff" },
        { name: "trebleC5", description: "This treble space note is on the third staff space from the bottom" },
        { name: "trebleC6", description: "This treble space note is on the second ledger space above the staff" },
        { name: "trebleC#4", description: "This treble sharp line note is on the first ledger line below the staff" },
        { name: "trebleC#5", description: "This treble sharp space note is on the third staff space from the bottom" },
        { name: "trebleD4", description: "This treble space note is below the first staff line" },
        { name: "trebleD5", description: "This treble line note is on the fourth staff line from the bottom" },
        { name: "trebleD#5", description: "This treble sharp line note is on the fourth staff line from the bottom" },
        { name: "trebleE4", description: "This treble line note is on the first staff line from the bottom" },
        { name: "trebleE5", description: "This treble space note is on the fourth staff space from the bottom" },
        { name: "trebleEb4", description: "This treble flat line note is on the first staff line from the bottom" },
        { name: "trebleE#5", description: "This treble sharp space note is on the first staff space from the top of the staff"},
        { name: "trebleF4", description: "This treble space note is on the first staff space from the bottom" },
        { name: "trebleF5", description: "This treble line note is on the fifth staff line from the bottom" },
        { name: "trebleF#5", description: "This treble sharp line note is on the top most line of the staff" },
        { name: "trebleG4", description: "This treble line note is on the second staff line from the bottom" },
        { name: "trebleG5", description: "This treble space note is above the fifth staff line" },
        { name: "trebleGb4", description: "This treble flat line note is on the second staff line from the bottom" },
        { name: "trebleG#4", description: "This treble sharp line note is on the second staff line from the bottom" },
        { name: "trebleGb5", description: "This treble flat space note is on the very top of the staff"}
    ]
}

export const allChords = [...(chords.crazy), ...(chords.note), ...(chords.triad)];

export default chords;
